jenkins-slaves/scala/Dockerfile.rhel7

some people run nexus not with http - in this case the build will fail as the replace is only going after https:// today

add http replace

---

ocp-templates/Dockerfile

Allow self-signed certificates (for minishift) or server certificates signed by a private CA
handled correctly for the oc cli.
It should also handle the case, where no customization is necessary.
In case you need to handle custom certificates, you must clone the ods-project-quickstarters project and add the CA to the CA-bundle.crt (will be described in the getting started guide).
And then push the updated version to your internal "fork". Don't like this too much, but haven't come to a better solution.

handdling of root ca

---

boilerplates/be-node-express/Jenkinsfile
boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-scala-akka/Jenkinsfile
boilerplates/be-springboot/Jenkinsfile
boilerplates/e2e-cypress/Jenkinsfile
boilerplates/fe-angular/Jenkinsfile
boilerplates/fe-ionic/Jenkinsfile
boilerplates/fe-react/Jenkinsfile

Following up on
https://github.com/opendevstack/ods-jenkins-shared-library/pull/31,
each quickstarter should point to production of the shared library on
the master branch. In the release branches, this has to be updated.
Closes #63.

Point to production of shared library

---

boilerplates/be-node-express/Jenkinsfile
boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-scala-akka/Jenkinsfile
boilerplates/be-springboot/Jenkinsfile
boilerplates/e2e-cypress/Jenkinsfile
boilerplates/fe-angular/Jenkinsfile
boilerplates/fe-ionic/Jenkinsfile
boilerplates/fe-react/Jenkinsfile

Now that quickstarters point to the production branch of the shared
library, they need to work with this version, not with the old tag.
Removing verbose is in line with this - the new version of the shared
library does not have a verbose setting anymore. It displays quite a
lot by default, and allows to enable debug mode if needed.
Fixes #69.

Add branchToEnvironmentMapping to Jenkinsfiles

---

rundeck-jobs/common/prepare-continuous-integration-rshiny.yaml
rundeck-jobs/common/prepare-continuous-integration.yaml
rundeck-jobs/common/verify global rundeck settings.yaml
rundeck-jobs/openshift/check insecure OC routes.yaml
rundeck-jobs/openshift/create-component.yaml
rundeck-jobs/openshift/create-projects.yaml
rundeck-jobs/openshift/create-rshiny.yaml
rundeck-jobs/openshift/delete-component.yaml
rundeck-jobs/openshift/delete-projects.yaml
rundeck-jobs/openshift/export-ocp-artifacts.yaml
rundeck-jobs/quickstarts/be_database.yaml
rundeck-jobs/quickstarts/be_node_express.yaml
rundeck-jobs/quickstarts/be_python_flask.yaml
rundeck-jobs/quickstarts/be_scala_akka.yaml
rundeck-jobs/quickstarts/be_spring_boot.yaml
rundeck-jobs/quickstarts/fe_angular.yaml
rundeck-jobs/quickstarts/fe_ionic_mobile.yaml
rundeck-jobs/quickstarts/fe_react.yaml
rundeck-jobs/quickstarts/jupyter_notebook.yaml
rundeck-jobs/quickstarts/rshiny_app.yaml

We don't need to setup a branch, we only want the latest state.
Also, there is no need to change into a subdirectory of the repository
in the clone/checkout step, because that "information" is lost in the
next command anyway.
Fixes #61.

Checkout production branch in detached state

---

ocp-templates/scripts/clone-project.sh

The deployment configs have a trigger set to the latest tag, therefore
we need to import that tag to auto-trigger a deployment, which is what
we want.

Import latest tag

---

boilerplates/be-node-express/Jenkinsfile
boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-scala-akka/Jenkinsfile
boilerplates/be-springboot/Jenkinsfile
boilerplates/fe-angular/Jenkinsfile
boilerplates/fe-ionic/Jenkinsfile
boilerplates/fe-react/Jenkinsfile
boilerplates/jupyter-notebook/Jenkinsfile
boilerplates/rshiny/Jenkinsfile

Since https://github.com/opendevstack/ods-jenkins-shared-library/pull/43
is merged, we need to remove the now obsolete stages from each
Jenkinsfile.

Remove obsolete stages

---

boilerplates/fe-angular/files/docker/nginx.vh.default.conf.nginx
boilerplates/fe-ionic/files/docker/nginx.vh.default.conf.nginx
boilerplates/fe-react/files/docker/nginx.vh.default.conf.nginx

Related issue #100:
Harden nginx config according to best practices. See also https://gist.github.com/plentz/6737338 and the work on the WAF api quickstarter (opendevstack/ods-core#43).
Affected FE-related quickstarters are:
* fe-angular
* fe-ionic
* fe-react

Harden nginx config according to best practices

---

boilerplates/fe-ionic/README.md
boilerplates/fe-ionic/files/package.json

- Add Ionic quickstarter README.md
- Update typescript dependency to **version 3.1.6**. Current version throws **types/jasmine** errors when serving the app and do not render.

Ionic quicstarter docs

---

ocp-templates/templates/cd-jenkins-webhook-proxy.yml

This way it is easier for users to see which branches are protected,
and also clearer how to change it. Also, it paves the way to allow
users to choose their own default in a future version of ODS when
those templates are applied via Tailor.
Related to https://github.com/opendevstack/ods-core/issues/107.

Configure PROTECTED_BRANCHES in template to make it more explicit

---

boilerplates/be-golang/Jenkinsfile
boilerplates/be-golang/README.md
boilerplates/be-golang/files/docker/Dockerfile
boilerplates/be-golang/files/main.go
boilerplates/be-golang/init.sh
boilerplates/be-golang/sonar-project.properties
jenkins-slaves/golang/Dockerfile.rhel7
jenkins-slaves/golang/ocp-config/Tailorfile
jenkins-slaves/golang/ocp-config/bc.yml
jenkins-slaves/golang/ocp-config/is.yml
rundeck-jobs/common/prepare-continuous-integration.yaml
rundeck-jobs/quickstarts/be-golang.yaml

Closes #255.
FYI @metmajer Would love to have your input even though I cannot assign you as reviewer atm ...

Implement Go quickstarter

---

ocp-templates/templates/cd-jenkins-master.yml
ocp-templates/templates/component-environment.yml

The default ratio was 10, which is quite high. This will lead OpenShift to oversubscribe the nodes to 10x their capacity. This can cause unexpected OOMKill events, and very large high load induced instability in the entire cluster. Therefore, it is better to reduce the ratio (here to 1.5x).
I would love to reduce the default requested amount, but some quickstarters consume quite a lot of memory, so we need a high default. Maybe in the future, we can allow every quickstarter to choose this value individually (e.g. the frontend components running only Nginx need far less).
Closes #277.

Update memory requests/limits

---

boilerplates/rshiny-app/docker/Dockerfile

Standard port 11371 is often blocked by company firewalls / proxy.
Use port 80 instead
fixes #298

Access keyserver using port 80

---

boilerplates/be-springboot/files/docker/Dockerfile
boilerplates/be-springboot/templates/build-4.10.gradle
jenkins-slaves/maven/Dockerfile.rhel7

I propose to make Java 11 the default for the ODS 1.2 slave. This should not break existing Java 8 applications.
In any case, we should think about versioning / tagging of slaves. I propose to do the same as with the shared library: from tags/branches we point to the corresponding tag ... as in, a `Jenkinsfile` in the `1.2.x` branch should point to a slave with tag `1.2.x` to avoid upgrade problems.
Closes #309

Install java-11-openjdk

---

ocp-templates/ocp-config/component-environment/component-template.yml

... so they are not covered by non-terminating quota scope
By adding a
spec:
completionDeadlineSeconds: 1800
the build pod becomes a "terminating" type container and a quota targeting non-terminating containers does no longer apply.
fixes #319

changing build pods to terminating type

---

ocp-templates/scripts/export_ocp_project_metadata.sh
ocp-templates/scripts/import_ocp_project_metadata.sh

Using `oc get --export` had the unintended side effect that more configuration is exported, as for example the image pull secret names.
Instead of adding filter code the deprecated `oc export` does not mention the secrets names and the association is created by OpenShift.
fixes #347 
Thanks to Michael for suggesting to revert to `oc export`!

Revert to oc export

---

ocp-templates/Dockerfile
ocp-templates/Dockerfile-with-config
rundeck-jobs/openshift/create-component.yaml
rundeck-jobs/openshift/create-projects.yaml
rundeck-jobs/openshift/create-rshiny.yaml
rundeck-jobs/quickstarts/ds_ml_service.yaml

- keep old way to build oc intact
- use Dockerfile-with-config and tag container oc-cfg
which use the container with the config embedded.
fixes #350

restore backward compatible script oc container

---

jenkins-slaves/nodejs10-angular/Dockerfile.rhel7
jenkins-slaves/nodejs8-angular/Dockerfile.rhel7
jenkins-slaves/python/Dockerfile.rhel7

update version of xvfb for nodejs slaves and cleanup dependency packages on python flask slave
closes #356

prepare jenkins slaves for 1.2.x release

---

boilerplates/fe-react/Jenkinsfile

Fix for https://github.com/opendevstack/ods-project-quickstarters/issues/364

fe-react: Fix env var that define where test reports are generated

---

boilerplates/be-springboot/init.sh
boilerplates/ds-ml-service/custom-create-components.sh
ocp-templates/scripts/clone-project.sh
ocp-templates/scripts/create-projects.sh
ocp-templates/scripts/export_ocp_project_metadata.sh
ocp-templates/scripts/import_ocp_project_metadata.sh
rundeck-jobs/common/verify global rundeck settings.yaml
rundeck-jobs/openshift/create-component.yaml
rundeck-jobs/openshift/create-projects.yaml
rundeck-jobs/openshift/create-rshiny.yaml
rundeck-jobs/openshift/delete-projects.yaml
rundeck-jobs/quickstarts/airflow.yaml
rundeck-jobs/quickstarts/be_python_flask.yaml
rundeck-jobs/quickstarts/be_scala_akka.yaml
rundeck-jobs/quickstarts/ds_ml_service.yaml

closes #340 
I have not done solid testing in production so this could be too late for a 1.2 release. 
Please review with care so that we do not end up breaking the release. 
Note that this may not hit all credential disclosures only where I readily expected them. I believe this is a good starting point however. 
The changes involve credentials which are explicitly available in scripts
with dedicated parameters or other context variables which carry:
- password arguments
- generated secrets
- openshift api tokens.
A. Changes made in rundeck jobs:
- Echo of `${option.openshift_api_token}` either replaced
with `<blinded>` or removed.
- Not using `set -x` (tracing) to avoid disclosure in executed commands.
NOTE:  Executing rundeck scripts with *Log level* `Debug` traces all
commands anyhow, …

Avoid disclosure of credentials

---

rundeck-jobs/quickstarts/be-golang.yaml

fix overlap of uuid rundeck jobs between golang and node-express
