opendevstack/ods-project-quickstarters

ocp-templates/scripts/import_ocp_project_metadata.sh

fix for #4 - with debug on, and exit if it cant' be located.

add debug and exit 1 - if source config can't be loaded

---

boilerplates/be-node-express/Jenkinsfile
boilerplates/be-node-express/files/docker/Dockerfile
boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-python-flask/files/docker/Dockerfile
boilerplates/be-scala-akka/Jenkinsfile
boilerplates/be-scala-akka/files/docker/Dockerfile
boilerplates/be-springboot/Jenkinsfile
boilerplates/be-springboot/files/docker/Dockerfile
boilerplates/e2e-cypress/Jenkinsfile
boilerplates/fe-angular/Jenkinsfile
boilerplates/fe-angular/files/docker/Dockerfile
boilerplates/fe-ionic/Jenkinsfile
boilerplates/fe-ionic/files/docker/Dockerfile
boilerplates/fe-react/Jenkinsfile
boilerplates/fe-react/files/docker/Dockerfile
ocp-templates/templates/bc-docker.yml

This makes use of the features introduced in https://github.com/opendevstack/ods-jenkins-shared-library/pull/8.

Upload artifacts directly to OpenShift

---

ocp-templates/Dockerfile

This pull requests changes the certificate handling for the oc cluster #12

Handle certificate from openshift cluster

---

ocp-templates/templates/rshiny-app.yml

flip version of authproxy in template

---

boilerplates/be-node-express/build.sh
boilerplates/be-scala-akka/build.sh
boilerplates/be-springboot/build.sh
boilerplates/fe-angular/build.sh

Otherwise we fill up disk space quickly.
Fixes #16.

Clean up intermediate containers during docker build

---

boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-python-flask/files/docker/Dockerfile
boilerplates/be-python-flask/files/docker/run.sh
jenkins-slaves/python/Dockerfile.rhel7

Update Python quickstarter to 3.7

---

boilerplates/be-node-express/Jenkinsfile
boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-scala-akka/Jenkinsfile
boilerplates/be-springboot/Jenkinsfile
boilerplates/e2e-cypress/Jenkinsfile
boilerplates/fe-angular/Jenkinsfile
boilerplates/fe-ionic/Jenkinsfile
boilerplates/fe-react/Jenkinsfile

Just noticed I didn't push this yet ... it's already in our BitBucket.

Point to specific tag of shared library

---

boilerplates/be-node-express/init.sh

added command to update the package.json to exclude directories 

---

CHANGELOG.md

Changed changelog format according to https://keepachangelog.com/en/1.0.0/

Changed format

---

boilerplates/jupyter-notebook/Jenkinsfile
boilerplates/renderJenkinsTemplate.sh
boilerplates/rshiny/Jenkinsfile
ocp-templates/scripts/create-rshiny-app.sh
ocp-templates/scripts/delete-component.sh
ocp-templates/scripts/delete-rshiny-app.sh
ocp-templates/templates/rshiny-app.yml
rundeck-jobs/common/prepare-continuous-integration-rshiny.yaml
rundeck-jobs/common/prepare-continuous-integration.yaml
rundeck-jobs/quickstarts/be_database.yaml
rundeck-jobs/quickstarts/be_node_express.yaml
rundeck-jobs/quickstarts/be_python_flask.yaml
rundeck-jobs/quickstarts/be_scala_akka.yaml
rundeck-jobs/quickstarts/be_spring_boot.yaml
rundeck-jobs/quickstarts/fe_angular.yaml
rundeck-jobs/quickstarts/fe_ionic_mobile.yaml
rundeck-jobs/quickstarts/fe_react.yaml
rundeck-jobs/quickstarts/jupyter_notebook.yaml
rundeck-jobs/quickstarts/rshiny_app.yaml

Build Jupyter/Rshiny via Jenkins

---

jenkins-slaves/maven/Dockerfile.rhel7
jenkins-slaves/maven/set_maven_proxy.sh

Bug/invalid settings xml - master

---

jenkins-slaves/maven/Dockerfile.rhel7
jenkins-slaves/maven/set_maven_proxy.sh

Fix invalid xml for 1.0.x

---

jenkins-slaves/nodejs8-angular/Dockerfile.rhel7

Quickfix only, we need a better way to make this more reliable in the future ...

Update version of xvfb

---

boilerplates/ds-ml-service/custom-create-components.sh
boilerplates/ds-ml-service/files/README.md

adding resource limits definition when creating ds-ml-service

---

boilerplates/fe-angular/init.sh

fix for https://github.com/opendevstack/ods-project-quickstarters/issues/129

change typescript version from "~2.7.2" to "2.8.0"

---

boilerplates/fe-angular/init.sh

fix for https://github.com/opendevstack/ods-project-quickstarters/issues/129

change typescript from 2.8.0 to 2.8.1

---

jenkins-slaves/python/Dockerfile.rhel7

python 3 slave fix - for 1.0x

---

jenkins-slaves/python/Dockerfile.rhel7

 python 3 slave - fix for master

---

ocp-templates/scripts/clone-project.sh
ocp-templates/scripts/import_ocp_project_metadata.sh

Fixes on the clone and import script to check and validate configuration

---

jenkins-slaves/python/Dockerfile.rhel7

python pip configured with ssl properly

---

boilerplates/ds-ml-service/files/build.bat

Added a windows batch file, similar to the 'build.sh' in order to run the quickstarter with docker-compose also on windows machines for local testing

DSI-44 added build.bat

---

ocp-templates/templates/bc-docker.yml

regression fix - follow up from #182 for 1.0.x

---

ocp-templates/templates/cd-jenkins-webhook-proxy.yml

Use jenkins serviceaccount for the webhook proxy

---

boilerplates/be-docker-plain/Jenkinsfile
boilerplates/be-node-express/Jenkinsfile
boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-scala-akka/Jenkinsfile
boilerplates/be-springboot/Jenkinsfile
boilerplates/ds-ml-service/Jenkinsfile
boilerplates/e2e-cypress/Jenkinsfile
boilerplates/fe-angular/Jenkinsfile
boilerplates/fe-ionic/Jenkinsfile
boilerplates/fe-react/Jenkinsfile
boilerplates/jupyter-notebook/Jenkinsfile
boilerplates/rshiny-app/Jenkinsfile

add jenkinsfile docs / shared lib link

---

ocp-templates/scripts/create-rshiny-app.sh
ocp-templates/scripts/delete-rshiny-app.sh

remove pipeline creation rshiny

---

ocp-templates/scripts/import_ocp_project_metadata.sh

move admin and remote token setup outside new project

---

CHANGELOG.md
boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-python-flask/files/src/test_requirements.txt
boilerplates/be-python-flask/files/src/tests/.coveragerc
boilerplates/be-python-flask/sonar-project.properties

improve sonarqube support on be-python-flask quickstarter

---

CHANGELOG.md
boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-python-flask/files/src/test_requirements.txt
boilerplates/be-python-flask/files/src/tests/.coveragerc
boilerplates/be-python-flask/sonar-project.properties
boilerplates/fe-angular/Jenkinsfile
boilerplates/fe-angular/README.md
boilerplates/fe-angular/build.sh
boilerplates/fe-angular/files/package.json
boilerplates/fe-angular/files/tslint.json
boilerplates/fe-angular/init.sh
boilerplates/fe-angular/sonar-project.properties

merging changes relating to #216 also into ODS 1.1.x branch

improve sonarqube support on quickstarters

---

boilerplates/be-python-flask/Jenkinsfile
boilerplates/be-python-flask/files/docker/Dockerfile
boilerplates/ds-ml-service/Jenkinsfile
boilerplates/ds-ml-service/files/docker-prediction/Dockerfile
boilerplates/ds-ml-service/files/docker-training/Dockerfile
boilerplates/jupyter-notebook/Jenkinsfile
boilerplates/jupyter-notebook/files/docker/Dockerfile

right nexus hosts to boilerplates: ds-ml-service, be-python-flash, jupyter-notebook
closes #235

adding ARG nexusHostWithoutScheme and right pip install to nexus 

---

boilerplates/fe-ionic/files/package.json

fixes https://github.com/opendevstack/ods-project-quickstarters/issues/242

add missing dependency

---

boilerplates/fe-angular/files/package.json
boilerplates/fe-angular/files/tslint.json

it can be added later via yarn add rxjs-tslint

yarn does not like rxjs-tslint, soon they will provide fix

---

boilerplates/be-python-flask/files/docker/Dockerfile

closes #250 
what happen? the builddeps where not being installed indeed...

submitting solution provided by @thowerner in github issue #250

---

boilerplates/ds-ml-service/Jenkinsfile

added a wait step between oc port-forward and training service execution

---

boilerplates/fe-react/README.md

for https://github.com/opendevstack/ods-project-quickstarters/issues/266

add contact persons #266

---

ocp-templates/scripts/clone-project.sh

Feature/skip tag master & allow to pass git branch to clone env sh

---

ocp-templates/scripts/clone-project.sh
ocp-templates/scripts/import_ocp_project_metadata.sh

closes #292  
fixes currently broken master

Feature/skip tag master - udpate 2

---

boilerplates/fe-ionic/files/README.md

Fix company mention

---

boilerplates/be-golang/Jenkinsfile
jenkins-slaves/golang/Dockerfile.rhel7

Create junit test report for golang quickstarter

---

ocp-templates/scripts/clone-project.sh

change required for https://github.com/opendevstack/ods-jenkins-shared-library/issues/109

arroba to ASCII for clone project script

---

ocp-templates/scripts/clone-project.sh

will fix https://github.com/opendevstack/ods-jenkins-shared-library/issues/109

fixes #ods-jenkins-shared-library/issues/109

---

boilerplates/fe-ionic/files/karma.conf.js
boilerplates/fe-ionic/files/package.json

This is fairly simple change, in relation to fe-angular one.

Added junit test reporter in ionic quickstarter openddevstack #299

---

boilerplates/be-python-flask/Jenkinsfile

related to -> Enable xml unit - unit test results on all quickstarters and refactor build stage #299

be-python-flask testResults to src/tests #299

---

boilerplates/jupyter-notebook/files/docker/Dockerfile
boilerplates/jupyter-notebook/files/docker/jupyter_notebook_config.json
boilerplates/jupyter-notebook/files/docker/requirements.txt
boilerplates/jupyter-notebook/files/docker/run.sh

solving:
- jupyter quickstarter app: Kernel won't start #268 
- jupyter quickstarter Error building Python based Quickstarters on OKD #295

switch to centos, volume/persistance enablement and extension management

---

boilerplates/ds-ml-service/Jenkinsfile
boilerplates/ds-ml-service/files/docker/Dockerfile
boilerplates/ds-ml-service/files/test/run_integration_tests.sh
boilerplates/ds-ml-service/files/test/run_unittests.sh
boilerplates/jupyter-notebook/files/docker/Dockerfile

fixes #295 for both jupyter-notebook and ds-ml-service

---

boilerplates/fe-react/init.sh

Fix for https://github.com/opendevstack/ods-project-quickstarters/issues/361

fe-react: Make sure npm i is run within node docker image

---

boilerplates/be-python-flask/Jenkinsfile

Fix for https://github.com/opendevstack/ods-project-quickstarters/issues/366

be-python-flask: Use default test location folder instead of custom

---

boilerplates/fe-vue/Jenkinsfile
boilerplates/fe-vue/files/package.json

Unit test results ouptuts with Junit XML for Vue QS

---

boilerplates/ds-ml-service/Jenkinsfile

ds-ml-service mro ready

---

boilerplates/fe-angular/init.sh

one liner sed append require line in karma conf

---

boilerplates/airflow/Jenkinsfile

tag image stage for airflow cluster quickstarter

---

boilerplates/ds-ml-service/Jenkinsfile

required due to https://github.com/opendevstack/ods-jenkins-shared-library/issues/135

mro update from ods-jenkins-shared-library issue 135

---

boilerplates/be-golang/sonar-project.properties

fixes https://github.com/opendevstack/ods-core/issues/190

adding sonarqube go plugin

---

boilerplates/be-golang/files/main_test.go

Add dummy test to Go quickstarter

---

rundeck-jobs/quickstarts/be-golang.yaml

Fix/rundeck go lang UUID overlap 1 2 x

---

ocp-templates/ocp-config/cd-jenkins-master/cd-jenkins-master.yml

jenkins master param for storage class data

---

boilerplates/airflow/Jenkinsfile

adding --trusted-host flag for pip install dependencies on airflow

---

ocp-templates/scripts/check_ocp_secure_routes.sh

reencrypt type check for check_ocp_secure_routes.sh

---

boilerplates/be-springboot/build.sh
boilerplates/be-springboot/templates/build-4.10.gradle
rundeck-jobs/common/prepare-continuous-integration.yaml

fix failing spring boot quickstarter Bugfix 440

---

jenkins-slaves/maven/Dockerfile.rhel7
jenkins-slaves/maven/contrib/settings.xml

Bug/missing nexus config for maven slave -> master

---

boilerplates/ds-ml-service/files/src/requirements.txt

ds-ml-service remote training fix

---

boilerplates/ds-ml-service/files/src/model/model_wrapper.py
boilerplates/ds-ml-service/files/src/requirements.txt
boilerplates/ds-ml-service/files/src/run.sh
boilerplates/ds-ml-service/files/src/services/prediction/app.py
boilerplates/ds-ml-service/files/src/services/training/app.py

run services with WSGI server - fix remote training

---

jenkins-slaves/python/Dockerfile.rhel7

fixes https://github.com/opendevstack/ods-quickstarters/issues/67

changes group of $HOME to give access to default user
